name: Обновление данных

on:
  schedule:
    - cron: "0/25 * * * *"   # Каждый час
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      models: read

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Клонирование репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Установка зависимостей
        run: |
          pip install -r requirements.txt

      - name: Запуск парсинга
        run: python src/main.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Сохранение дайджеста в репозиторий
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Автоматическое обновление дайджеста"
          file_pattern: "digests/*.md"
